import { Product, Service, TeamMember, Client, Testimonial, CompanyHistory, Certification } from '@/types'

export const mockProducts: Product[] = [
  {
    id: '1',
    slug: 'clp- siemens-s7-1200',
    name: 'CLP Siemens S7-1200',
    category: 'clps',
    description: 'Controlador Lógico Programável compacto para aplicações de automação industrial.',
    fullDescription: 'O Siemens S7-1200 é um CLP compacto e poderoso, ideal para aplicações de automação de pequeno a médio porte. Com design modular e recursos avançados de comunicação, oferece excelente desempenho e flexibilidade para processos industriais.',
    image: '/images/products/s7-1200.jpg',
    images: [
      '/images/products/s7-1200-1.jpg',
      '/images/products/s7-1200-2.jpg',
      '/images/products/s7-1200-3.jpg',
    ],
    specifications: [
      { name: 'Memória de Programa', value: '100 KB', unit: 'KB' },
      { name: 'Memória de Dados', value: '50 KB', unit: 'KB' },
      { name: 'Entradas Digitais', value: '14' },
      { name: 'Saídas Digitais', value: '10' },
      { name: 'Entradas Analógicas', value: '2' },
      { name: 'Protocolos', value: 'PROFINET, Ethernet/IP' },
    ],
    features: [
      'Design compacto',
      'Programação intuitiva com TIA Portal',
      'Integração com web server',
      'Segurança integrada',
      'Comunicação PROFINET nativa',
    ],
    applications: [
      'Máquinas de embalagem',
      'Sistemas de transporte',
      'Controle de processos',
      'Automação predial',
    ],
    datasheet: '/docs/s7-1200-datasheet.pdf',
    manual: '/docs/s7-1200-manual.pdf',
    inStock: true,
    featured: true,
    tags: ['siemens', 'clp', 'automacao', 'industrial'],
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: '2',
    slug: 'sensor-indutivo-ifm-ig603',
    name: 'Sensor Indutivo IFM IG603',
    category: 'sensores',
    description: 'Sensor de proximidade indutivo para detecção de metais em ambiente industrial.',
    fullDescription: 'O sensor indutivo IFM IG603 oferece detecção confiável de metais em condições industriais adversas. Com construção robusta e alta precisão, é ideal para aplicações de posicionamento e contagem.',
    image: '/images/products/ifm-ig603.jpg',
    images: [
      '/images/products/ifm-ig603-1.jpg',
      '/images/products/ifm-ig603-2.jpg',
    ],
    specifications: [
      { name: 'Distância Sensora', value: '3', unit: 'mm' },
      { name: 'Tipo', value: 'M12 x 1' },
      { name: 'Alimentação', value: '24 VDC' },
      { name: 'Saída', value: 'PNP/NPN' },
      { name: 'Proteção', value: 'IP67' },
    ],
    features: [
      'Alta precisão',
      'Proteção IP67',
      'LED indicador',
      'Instalação simplificada',
      'Longa vida útil',
    ],
    applications: [
      'Detecção de peças metálicas',
      'Controle de posicionamento',
      'Sistemas de esteira',
      'Máquinas operatrizes',
    ],
    datasheet: '/docs/ifm-ig603-datasheet.pdf',
    inStock: true,
    featured: true,
    tags: ['ifm', 'sensor', 'indutivo', 'proximidade'],
    createdAt: new Date('2024-01-18'),
    updatedAt: new Date('2024-01-22'),
  },
  {
    id: '3',
    slug: 'atuador-pneumatico-festo-dfp',
    name: 'Atuador Pneumático FESTO DFP',
    category: 'atuadores',
    description: 'Cilindro pneumático de dupla ação para movimentação industrial.',
    fullDescription: 'O cilindro pneumático FESTO DFP é projetado para aplicações que exigem movimento linear preciso e confiável. Com construção de alta qualidade e baixo consumo de ar, oferece excelente desempenho em ambiente industrial.',
    image: '/images/products/festo-dfp.jpg',
    images: [
      '/images/products/festo-dfp-1.jpg',
      '/images/products/festo-dfp-2.jpg',
    ],
    specifications: [
      { name: 'Diâmetro', value: '50', unit: 'mm' },
      { name: 'Curso', value: '200', unit: 'mm' },
      { name: 'Pressão', value: '6', unit: 'bar' },
      { name: 'Tipo', value: 'Dupla ação' },
      { name: 'Fixação', value: 'Traseira' },
    ],
    features: [
      'Baixo consumo de ar',
      'Construção robusta',
      'Ampla faixa de cursos',
      'Baixo ruído',
      'Alta confiabilidade',
    ],
    applications: [
      'Robótica industrial',
      'Máquinas de embalagem',
      'Sistemas de transporte',
      'Equipamentos de teste',
    ],
    inStock: true,
    featured: false,
    tags: ['festo', 'atuador', 'pneumatico', 'cilindro'],
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-25'),
  },
  {
    id: '4',
    slug: 'painel-controle-industrial',
    name: 'Painel de Controle Industrial',
    category: 'painels',
    description: 'Painel de controle completo para automação industrial com IHM integrada.',
    fullDescription: 'Painel de controle industrial robusto e completo, projetado para operação em ambientes severos. Com IHM touchscreen de alta resolução e múltiplas opções de comunicação.',
    image: '/images/products/painel-controle.jpg',
    images: [
      '/images/products/painel-controle.jpg',
      '/images/products/painel-controle-2.jpg',
    ],
    specifications: [
      { name: 'Tela', value: '10.1', unit: 'polegadas' },
      { name: 'Resolução', value: '1024x600' },
      { name: 'IP', value: '65' },
      { name: 'Temperatura', value: '0-60', unit: '°C' },
      { name: 'Alimentação', value: '24 VDC' },
    ],
    features: [
      'Touchscreen capacitivo',
      'Proteção IP65',
      'Múltiplas interfaces',
      'Design robusto',
      'Fácil instalação',
    ],
    applications: [
      'Controle de processos',
      'Monitoramento industrial',
      'Automação predial',
      'Sistemas de bombas',
    ],
    inStock: true,
    featured: true,
    tags: ['painel', 'controle', 'ihm', 'industrial'],
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-28'),
  },
  {
    id: '5',
    slug: 'software-scada-empresarial',
    name: 'Software SCADA Empresarial',
    category: 'software',
    description: 'Sistema completo de supervisão e controle para processos industriais.',
    fullDescription: 'Software SCADA empresarial com recursos avançados de monitoramento, controle e análise de dados. Interface intuitiva e escalável para indústrias de todos os portes.',
    image: '/images/products/software-scada.jpg',
    images: [
      '/images/products/software-scada.jpg',
      '/images/products/software-scada-2.jpg',
    ],
    specifications: [
      { name: 'Licença', value: 'Perpétua' },
      { name: 'Pontos', value: 'Até 10000' },
      { name: 'Clients', value: 'Ilimitados' },
      { name: 'Base de Dados', value: 'SQL Server/MySQL' },
      { name: 'Relatórios', value: 'Customizáveis' },
    ],
    features: [
      'Interface web responsiva',
      'Alertas personalizados',
      'Histórico completo',
      'Gráficos em tempo real',
      'Integração ERP',
    ],
    applications: [
      'Indústria química',
      'Tratamento de água',
      'Geração de energia',
      'Linha de produção',
    ],
    inStock: true,
    featured: false,
    tags: ['scada', 'software', 'supervisao', 'controle'],
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-30'),
  },
  {
    id: '6',
    slug: 'interface-hmi-touch',
    name: 'Interface HMI Touch Avançada',
    category: 'interfaces',
    description: 'Interface homem-máquina touchscreen com gráficos avançados.',
    fullDescription: 'HMI touchscreen de alta performance com gráficos avançados e múltiplas opções de comunicação. Ideal para modernização de painéis de controle industriais.',
    image: '/images/products/interface-hmi.jpg',
    images: [
      '/images/products/interface-hmi.jpg',
      '/images/products/interface-hmi-2.jpg',
    ],
    specifications: [
      { name: 'Tela', value: '7', unit: 'polegadas' },
      { name: 'Resolução', value: '800x480' },
      { name: 'Cores', value: '65K' },
      { name: 'Comunicação', value: 'Ethernet, RS485' },
      { name: 'Memória', value: '128MB' },
    ],
    features: [
      'Gráficos vetoriais',
      'Alarmes configuráveis',
      'Receitas dinâmicas',
      'Backup automático',
      'Multi-idioma',
    ],
    applications: [
      'Máquinas operatrizes',
      'Empacotadeiras',
      'Sistemas dosagem',
      'Controle de qualidade',
    ],
    inStock: true,
    featured: true,
    tags: ['hmi', 'interface', 'touchscreen', 'graficos'],
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-25'),
  },
  {
    id: '7',
    slug: 'gateway-comunicacao-industrial',
    name: 'Gateway de Comunicação Industrial',
    category: 'comunicacao',
    description: 'Gateway para integração de diferentes protocolos industriais.',
    fullDescription: 'Gateway industrial robusto para integração entre diferentes protocolos de comunicação. Suporta múltiplos padrões e configuração flexível.',
    image: '/images/products/gateway-comunicacao.jpg',
    images: [
      '/images/products/gateway-comunicacao.jpg',
      '/images/products/gateway-comunicacao-2.jpg',
    ],
    specifications: [
      { name: 'Protocolos', value: 'Modbus, PROFINET, Ethernet/IP' },
      { name: 'Portas', value: '4 Ethernet + 2 Serial' },
      { name: 'Taxa', value: '100', unit: 'Mbps' },
      { name: 'Temperatura', value: '-40 a 85', unit: '°C' },
      { name: 'Alimentação', value: '24 VDC' },
    ],
    features: [
      'Configuração web',
      'Diagnóstico avançado',
      'Isolação galvânica',
      'Hot-swap',
      'LEDs de status',
    ],
    applications: [
      'Integração de sistemas',
      'Modernização de CLPs',
      'Conexão com ERPs',
      'Coleta de dados',
    ],
    inStock: true,
    featured: false,
    tags: ['gateway', 'comunicacao', 'protocolo', 'integracao'],
    createdAt: new Date('2024-01-03'),
    updatedAt: new Date('2024-01-22'),
  },
]

export const mockServices: Service[] = [
  {
    id: '1',
    slug: 'projetos-de-automacao',
    name: 'Projetos de Automação',
    description: 'Desenvolvimento completo de projetos de automação industrial sob medida.',
    fullDescription: 'Oferecemos desenvolvimento completo de projetos de automação industrial, desde o concepção inicial até a implementação final. Nossa equipe técnica qualificada projeta sistemas eficientes que otimizam processos e aumentam a produtividade.',
    icon: 'settings',
    image: '/images/services/automacao.jpg',
    benefits: [
      'Aumento da produtividade',
      'Redução de custos operacionais',
      'Melhoria da qualidade do produto',
      'Segurança operacional',
      'Monitoramento em tempo real',
    ],
    process: [
      {
        id: '1',
        title: 'Análise e Diagnóstico',
        description: 'Estudo detalhado do processo atual e identificação de oportunidades de melhoria.',
        icon: 'search',
        duration: '5-7 dias',
      },
      {
        id: '2',
        title: 'Projeto Conceitual',
        description: 'Desenvolvimento da solução técnica e definição dos requisitos do sistema.',
        icon: 'drafting-compass',
        duration: '3-5 dias',
      },
      {
        id: '3',
        title: 'Implementação',
        description: 'Instalação e configuração dos equipamentos e sistemas de automação.',
        icon: 'wrench',
        duration: '10-20 dias',
      },
      {
        id: '4',
        title: 'Comissionamento',
        description: 'Testes, ajustes finos e treinamento da equipe operacional.',
        icon: 'play-circle',
        duration: '2-3 dias',
      },
    ],
    duration: '20-35 dias',
    featured: true,
    tags: ['automacao', 'projetos', 'consultoria'],
  },
  {
    id: '2',
    slug: 'manutencao-industrial',
    name: 'Manutenção Preventiva e Corretiva',
    description: 'Serviços completos de manutenção para garantir a disponibilidade de seus equipamentos.',
    fullDescription: 'Nossos serviços de manutenção industrial visam garantir a máxima disponibilidade e vida útil dos seus equipamentos. Atuamos tanto na manutenção preventiva quanto na corretiva, com equipes especializadas e rápida resposta.',
    icon: 'tool',
    image: '/images/services/manutencao.jpg',
    benefits: [
      'Redução de paradas não planejadas',
      'Aumento da vida útil dos equipamentos',
      'Economia a longo prazo',
      'Segurança operacional',
      'Disponibilidade 24/7',
    ],
    process: [
      {
        id: '1',
        title: 'Diagnóstico',
        description: 'Avaliação do estado atual dos equipamentos e identificação de necessidades.',
        icon: 'clipboard-list',
        duration: '1-2 dias',
      },
      {
        id: '2',
        title: 'Planejamento',
        description: 'Definição do cronograma e recursos necessários para a manutenção.',
        icon: 'calendar',
        duration: '1 dia',
      },
      {
        id: '3',
        title: 'Execução',
        description: 'Realização dos serviços de manutenção programada ou emergencial.',
        icon: 'wrench',
        duration: 'Variável',
      },
      {
        id: '4',
        title: 'Verificação',
        description: 'Testes de funcionamento e entrega do equipamento em perfeitas condições.',
        icon: 'check-circle',
        duration: '1 dia',
      },
    ],
    duration: 'Conforme necessidade',
    featured: true,
    tags: ['manutencao', 'suporte', 'corretiva', 'preventiva'],
  },
  {
    id: '3',
    slug: 'treinamento-tecnico',
    name: 'Treinamento Técnico',
    description: 'Capacitação prática para equipes operacionais e de manutenção.',
    fullDescription: 'Oferecemos programas de treinamento técnico desenvolvidos para capacitar equipes na operação e manutenção de sistemas de automação industrial. Cursos práticos com foco nas necessidades específicas de cada cliente.',
    icon: 'graduation-cap',
    image: '/images/services/treinamento.jpg',
    benefits: [
      'Equipes capacitadas e autônomas',
      'Redução de chamados de suporte',
      'Operação mais eficiente',
      'Segurança no trabalho',
      'Atualização tecnológica',
    ],
    process: [
      {
        id: '1',
        title: 'Levantamento de Necessidades',
        description: 'Identificação das competências e conhecimentos necessários.',
        icon: 'users',
        duration: '1 dia',
      },
      {
        id: '2',
        title: 'Programação',
        description: 'Desenvolvimento do conteúdo e definição do cronograma do treinamento.',
        icon: 'calendar-alt',
        duration: '2-3 dias',
      },
      {
        id: '3',
        title: 'Execução do Treinamento',
        description: 'Aulas teóricas e práticas com equipamentos reais.',
        icon: 'chalkboard-teacher',
        duration: '2-5 dias',
      },
      {
        id: '4',
        title: 'Avaliação',
        description: 'Testes práticos e certificação dos participantes.',
        icon: 'award',
        duration: '1 dia',
      },
    ],
    duration: '8-15 horas',
    featured: false,
    tags: ['treinamento', 'capacitacao', 'curso'],
  },
]

export const mockTeamMembers: TeamMember[] = [
  {
    id: '1',
    name: 'João Silva',
    role: 'Diretor Técnico',
    bio: 'Engenheiro Eletricista com 20 anos de experiência em automação industrial. Especialista em sistemas de controle e CLPs.',
    image: '/images/team/joao-silva.jpg',
    email: 'joao.silva@mako.ind.br',
    phone: '(85) 98765-4321',
    linkedin: 'https://linkedin.com/in/joaosilva',
    order: 1,
  },
  {
    id: '2',
    name: 'Maria Santos',
    role: 'Gerente de Projetos',
    bio: 'Engenheira de Controle e Automação com 15 anos de experiência em gestão de projetos industriais complexos.',
    image: '/images/team/maria-santos.jpg',
    email: 'maria.santos@mako.ind.br',
    phone: '(85) 98765-4322',
    linkedin: 'https://linkedin.com/in/mariasantos',
    order: 2,
  },
  {
    id: '3',
    name: 'Carlos Oliveira',
    role: 'Coordenador de Manutenção',
    bio: 'Técnico em Eletrotécnica com especialização em manutenção preditiva e corretiva de sistemas industriais.',
    image: '/images/team/carlos-oliveira.jpg',
    email: 'carlos.oliveira@mako.ind.br',
    phone: '(85) 98765-4323',
    linkedin: 'https://linkedin.com/in/carlosoliveira',
    order: 3,
  },
  {
    id: '4',
    name: 'Ana Costa',
    role: 'Engenheira de Automação',
    bio: 'Engenheira de Automação com experiência em programação de CLPs, IHMs e sistemas SCADA.',
    image: '/images/team/ana-costa.jpg',
    email: 'ana.costa@mako.ind.br',
    phone: '(85) 98765-4324',
    linkedin: 'https://linkedin.com/in/anacosta',
    order: 4,
  },
]

export const mockClients: Client[] = [
  {
    id: '1',
    name: 'Indústria Alimentícia XYZ',
    logo: '/images/clients/client-1.png',
    website: 'https://client1.com',
    description: 'Soluções completas de automação para linha de produção',
    featured: true,
  },
  {
    id: '2',
    name: 'Metalúrgica ABC',
    logo: '/images/clients/client-2.png',
    website: 'https://client2.com',
    description: 'Automação de prensas e sistemas de controle',
    featured: true,
  },
  {
    id: '3',
    name: 'Química Brasil',
    logo: '/images/clients/client-3.png',
    description: 'Controle de processos químicos e segurança industrial',
    featured: false,
  },
  {
    id: '4',
    name: 'Têxtil Sul',
    logo: '/images/clients/client-4.png',
    description: 'Automação de tear e sistemas de qualidade',
    featured: false,
  },
  {
    id: '5',
    name: 'Logística Express',
    logo: '/images/clients/client-5.png',
    description: 'Sistemas de transporte e armazenagem automatizados',
    featured: false,
  },
  {
    id: '6',
    name: 'Energia Verde',
    logo: '/images/clients/client-6.png',
    description: 'Controle de sistemas de energia e monitoramento',
    featured: false,
  },
]

export const mockTestimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Roberto Mendes',
    role: 'Gerente de Manutenção',
    company: 'Indústria Alimentícia XYZ',
    image: '/images/testimonials/roberto.jpg',
    content: 'A Mako transformou completamente nosso processo produtivo. A automação instalada aumentou nossa produtividade em 40% e reduziu os índices de defeito. Equipe extremamente competente e dedicada.',
    rating: 5,
    featured: true,
  },
  {
    id: '2',
    name: 'Luciana Ferreira',
    role: 'Diretora Industrial',
    company: 'Metalúrgica ABC',
    image: '/images/testimonials/luciana.jpg',
    content: 'Contratamos a Mako para modernizar nossas prensas e o resultado superou todas as expectativas. O atendimento técnico foi excepcional e o projeto foi entregue no prazo.',
    rating: 5,
    featured: true,
  },
  {
    id: '3',
    name: 'Pedro Costa',
    role: 'Engenheiro Chefe',
    company: 'Química Brasil',
    image: '/images/testimonials/pedro.jpg',
    content: 'Os serviços de manutenção preventiva da Mako garantiram a estabilidade de nossas operações. Excelente suporte técnico e rápida resposta quando necessário.',
    rating: 4,
    featured: false,
  },
]

export const mockCompanyHistory: CompanyHistory[] = [
  {
    year: '2015',
    title: 'Fundação da Mako',
    description: 'Início das atividades com foco em soluções de automção para pequenas e médias indústrias.',
    image: '/images/history/2015.jpg',
  },
  {
    year: '2017',
    title: 'Expansão do Portfólio',
    description: 'Ampliação da linha de produtos e serviços, incluindo manutenção industrial completa.',
    image: '/images/history/2017.jpg',
  },
  {
    year: '2019',
    title: 'Certificação ISO 9001',
    description: 'Conquista da certificação ISO 9001, reconhecendo a qualidade de nossos processos.',
    image: '/images/history/2019.jpg',
  },
  {
    year: '2021',
    title: 'Digitalização de Serviços',
    description: 'Implementação de sistemas de monitoramento remoto e suporte técnico 24/7.',
    image: '/images/history/2021.jpg',
  },
  {
    year: '2023',
    title: 'Expansão Nacional',
    description: 'Abertura de filiais em outros estados e consolidação como referência nacional.',
    image: '/images/history/2023.jpg',
  },
]

export const mockCertifications: Certification[] = [
  {
    id: '1',
    name: 'ISO 9001:2015',
    description: 'Sistema de Gestão da Qualidade para projeto e implementação de soluções de automação industrial.',
    image: '/images/certifications/iso-9001.jpg',
    validUntil: '2026-12-31',
    issuer: 'SGS Brasil',
  },
  {
    id: '2',
    name: 'ABNT NBR 5410',
    description: 'Certificação em instalações elétricas de baixa tensão conforme normas brasileiras.',
    image: '/images/certifications/nbr-5410.jpg',
    validUntil: '2025-12-31',
    issuer: 'ABNT',
  },
  {
    id: '3',
    name: 'NR-12',
    description: 'Segurança no Trabalho em Máquinas e Equipamentos.',
    image: '/images/certifications/nr-12.jpg',
    issuer: 'Ministério do Trabalho',
  },
  {
    id: '4',
    name: 'Certificação de Competência Técnica',
    description: 'Reconhecimento da competência técnica em automção industrial.',
    image: '/images/certifications/competencia-tecnica.jpg',
    validUntil: '2026-06-30',
    issuer: 'CREA-CE',
  },
]