import { Service, TeamMember, Client, Testimonial, CompanyHistory, Certification } from '@/types'
export const mockServices: Service[] = [
  {
    id: '1',
    slug: 'front-end-packages',
    name: 'Front-End Packages (FEP)',
    description: 'Elaboração de pacotes de premissas e concepção de projetos industriais.',
    fullDescription: 'Elaboração de pacotes de premissas e concepção de projetos industriais, incluindo análise EVA, estruturação organizacional, especificações de produto e controle de qualidade.',
    icon: 'package',
    image: '/images/services/fep.jpg',
    benefits: [
      'Análise EVA e Estruturas Organizacionais',
      'Especificações de Produto e Controle de Qualidade',
      'Análise de Constructability',
      'PFDs e EFDs',
      'HAZOP e P&D',
    ],
    process: [
      {
        id: '1',
        title: 'Análise Inicial',
        description: 'Estudo das premissas do projeto e definição de escopo.',
        icon: 'search',
        duration: '5-7 dias',
      },
      {
        id: '2',
        title: 'Desenvolvimento FEP',
        description: 'Elaboração do Front End Package completo.',
        icon: 'drafting-compass',
        duration: '15-30 dias',
      },
      {
        id: '3',
        title: 'Revisão Técnica',
        description: 'Validação técnica e ajustes necessários.',
        icon: 'check-circle',
        duration: '5-10 dias',
      },
      {
        id: '4',
        title: 'Entrega',
        description: 'Apresentação final e aprovação do cliente.',
        icon: 'award',
        duration: '2-3 dias',
      },
    ],
    duration: '30-50 dias',
    featured: true,
    tags: ['FEP', 'projetos', 'engenharia'],
  },
  {
    id: '2',
    slug: 'financiamento-captacao-recursos',
    name: 'Financiamento e Captação de Recursos',
    description: 'Projetos de viabilidade econômica e consultoria para financiamentos.',
    fullDescription: 'Elaboração de projetos de viabilidade econômica e consultoria junto a instituições financeiras e entidades públicas para captação de recursos.',
    icon: 'dollar-sign',
    image: '/images/services/financiamento.jpg',
    benefits: [
      'Projetos de Viabilidade Econômica',
      'Consultoria junto a Instituições Financeiras',
      'Elaboração de Estudos para Financiamentos',
      'Acesso a linhas de crédito específicas',
    ],
    process: [
      {
        id: '1',
        title: 'Diagnóstico',
        description: 'Análise das necessidades e objetivos do cliente.',
        icon: 'search',
        duration: '3-5 dias',
      },
      {
        id: '2',
        title: 'Elaboração',
        description: 'Desenvolvimento do projeto de viabilidade.',
        icon: 'drafting-compass',
        duration: '10-20 dias',
      },
      {
        id: '3',
        title: 'Consultoria',
        description: 'Acompanhamento junto às instituições financeiras.',
        icon: 'users',
        duration: 'Variável',
      },
      {
        id: '4',
        title: 'Resultado',
        description: 'Conclusão do processo de financiamento.',
        icon: 'award',
        duration: 'Conforme aprovação',
      },
    ],
    duration: '60-90 dias',
    featured: true,
    tags: ['financiamento', 'viabilidade', 'consultoria'],
  },
  {
    id: '3',
    slug: 'projetos-industriais',
    name: 'Elaboração de Projetos Industriais',
    description: 'Projetos civis, elétricos, mecânicos e ambientais em modelagem BIM.',
    fullDescription: 'Elaboração de projetos industriais completos incluindo projetos ambientais, engenharia de detalhamento em BIM, projetos civis, elétricos, mecânicos e de instrumentação.',
    icon: 'hard-hat',
    image: '/images/services/projetos.jpg',
    benefits: [
      'Projetos em Modelagem BIM',
      'Projetos Ambientais (RAS, EVA, EIA, RIMA)',
      'Licenciamento Ambiental (LP, LI, LO)',
      'Projetos Civis, Elétricos e Mecânicos',
      'SPDA, Aterramento e NR10, NR12, NR13, NR18',
    ],
    process: [
      {
        id: '1',
        title: 'Concepção',
        description: 'Definição das premissas técnicas e arquitetônicas.',
        icon: 'search',
        duration: '10-15 dias',
      },
      {
        id: '2',
        title: 'Projeto Básico',
        description: 'Desenvolvimento do projeto básico completo.',
        icon: 'drafting-compass',
        duration: '30-60 dias',
      },
      {
        id: '3',
        title: 'Detalhamento',
        description: 'Elaboração do projeto executivo em BIM.',
        icon: 'wrench',
        duration: '60-120 dias',
      },
      {
        id: '4',
        title: 'Validação',
        description: 'Revisão técnica e aprovação final.',
        icon: 'check-circle',
        duration: '15-30 dias',
      },
    ],
    duration: '120-225 dias',
    featured: true,
    tags: ['projetos', 'BIM', 'engenharia'],
  },
  {
    id: '4',
    slug: 'suprimentos-aquisicoes',
    name: 'Assessoria em Suprimentos e Aquisições',
    description: 'Homologação de fornecedores e elaboração de editais de concorrência.',
    fullDescription: 'Serviços de homologação de fornecedores de bens e serviços, elaboração de editais de concorrência e licitação técnica, análise e equalização de propostas técnicas.',
    icon: 'shopping-cart',
    image: '/images/services/suprimentos.jpg',
    benefits: [
      'Homologação de Fornecedores',
      'Editais de Concorrência e Licitação Técnica',
      'Análise e Equalização de Propostas',
      'Assessoria na Contratação',
    ],
    process: [
      {
        id: '1',
        title: 'Mapeamento',
        description: 'Identificação de fornecedores qualificados.',
        icon: 'search',
        duration: '5-10 dias',
      },
      {
        id: '2',
        title: 'Elaboração',
        description: 'Criação de editais e especificações técnicas.',
        icon: 'drafting-compass',
        duration: '10-20 dias',
      },
      {
        id: '3',
        title: 'Análise',
        description: 'Avaliação técnica das propostas recebidas.',
        icon: 'check-circle',
        duration: '15-30 dias',
      },
      {
        id: '4',
        title: 'Contratação',
        description: 'Formalização e acompanhamento.',
        icon: 'award',
        duration: '10-15 dias',
      },
    ],
    duration: '40-75 dias',
    featured: false,
    tags: ['suprimentos', 'licitação', 'fornecedores'],
  },
  {
    id: '5',
    slug: 'obras-instalacoes',
    name: 'Obras e Instalações',
    description: 'Execução de obras civis, elétricas, mecânicas e de segurança.',
    fullDescription: 'Execução de obras e instalações industriais completas incluindo civil, elétrica, mecânica e segurança. Adequação de equipamentos às normas NR10, NR12 e NR13.',
    icon: 'construction',
    image: '/images/services/obras.jpg',
    benefits: [
      'Obras Civis (Fundações, Infraestrutura, Superestrutura)',
      'Instalações Elétricas (Baixa e Média Tensão)',
      'Instalações Mecânicas (Pipe Rack, Tubulações)',
      'Segurança (Combate a Incêndio, SPDA, Linhas de Vida)',
      'Mão de Obra Especializada',
    ],
    process: [
      {
        id: '1',
        title: 'Planejamento',
        description: 'Elaboração do cronograma e planejamento executivo.',
        icon: 'calendar',
        duration: '15-30 dias',
      },
      {
        id: '2',
        title: 'Execução Civil',
        description: 'Execução das obras civis.',
        icon: 'hard-hat',
        duration: 'Variável',
      },
      {
        id: '3',
        title: 'Instalações',
        description: 'Execução das instalações elétricas e mecânicas.',
        icon: 'wrench',
        duration: 'Variável',
      },
      {
        id: '4',
        title: 'Entrega',
        description: 'Testes, comissionamento e entrega final.',
        icon: 'award',
        duration: '15-30 dias',
      },
    ],
    duration: 'Conforme projeto',
    featured: true,
    tags: ['obras', 'instalações', 'construção'],
  },
  {
    id: '6',
    slug: 'manutencoes',
    name: 'Manutenções',
    description: 'Manutenção preventiva, preditiva e corretiva de sistemas industriais.',
    fullDescription: 'Serviços de manutenção preventiva, preditiva e corretiva de sistemas elétricos-mecânicos, sistemas de ar-condicionado e elaboração de PMOC.',
    icon: 'tool',
    image: '/images/services/manutencao.jpg',
    benefits: [
      'Manutenção Preventiva, Preditiva e Corretiva',
      'Sistemas de Ar-condicionado e PMOC',
      'Equipes Técnicas Especializadas com KPIs',
      'Suporte de Engenharia Especializada',
      'Disponibilidade 24/7',
    ],
    process: [
      {
        id: '1',
        title: 'Diagnóstico',
        description: 'Avaliação do estado atual dos equipamentos.',
        icon: 'search',
        duration: '3-5 dias',
      },
      {
        id: '2',
        title: 'Planejamento',
        description: 'Definição do cronograma de manutenção.',
        icon: 'calendar',
        duration: '2-3 dias',
      },
      {
        id: '3',
        title: 'Execução',
        description: 'Realização dos serviços de manutenção.',
        icon: 'wrench',
        duration: 'Variável',
      },
      {
        id: '4',
        title: 'Relatório',
        description: 'Emissão de relatórios e indicadores.',
        icon: 'check-circle',
        duration: '1-2 dias',
      },
    ],
    duration: 'Contínuo',
    featured: true,
    tags: ['manutenção', 'preventiva', 'corretiva'],
  },
  {
    id: '7',
    slug: 'coordenacao-fiscalizacao',
    name: 'Coordenação e Fiscalização de Obras e Serviços',
    description: 'Controle de qualidade, HSSE e supervisão físico-financeira.',
    fullDescription: 'Serviços de coordenação e fiscalização de obras e serviços, incluindo controle de qualidade de engenharia e construção, supervisão de saúde, meio ambiente e segurança (HSSE).',
    icon: 'clipboard',
    image: '/images/services/fiscalizacao.jpg',
    benefits: [
      'Controle de Qualidade de Engenharia & Construção',
      'Supervisão HSSE (Saúde, Meio Ambiente e Segurança)',
      'Supervisão e Controle da Evolução Físico-Financeira',
      'Emissão de Relatórios e Indicadores',
    ],
    process: [
      {
        id: '1',
        title: 'Setup',
        description: 'Definição de processos e procedimentos.',
        icon: 'clipboard-list',
        duration: '5-10 dias',
      },
      {
        id: '2',
        title: 'Execução',
        description: 'Acompanhamento contínuo da obra.',
        icon: 'eye',
        duration: 'Durante toda a obra',
      },
      {
        id: '3',
        title: 'Controle',
        description: 'Monitoramento de indicadores.',
        icon: 'bar-chart',
        duration: 'Contínuo',
      },
      {
        id: '4',
        title: 'Relatórios',
        description: 'Emissão de relatórios periódicos.',
        icon: 'file-text',
        duration: 'Conforme demanda',
      },
    ],
    duration: 'Durante toda a obra',
    featured: false,
    tags: ['fiscalização', 'controle', 'qualidade'],
  },
]

export const mockTeamMembers: TeamMember[] = [
  {
    id: '1',
    name: 'Henrique Daniel de Cavalcante Carvalho',
    role: 'Sócio-Presidente | Fundador',
    bio: 'Engenheiro Civil, empresário e escritor, é fundador e Sócio-Presidente da empresa. Possui sólida atuação nas áreas de gerenciamento, qualidade total e projetos industriais, acumulando mais de 30 anos de experiência.',
    image: '/images/team/Henrique Daniel de Cavalcante Carvalho.png',
    email: 'contato@mako.ind.br',
    linkedin: 'https://www.linkedin.com/company/makosolucoesindustriais',
    order: 1,
  },
  {
    id: '2',
    name: 'Carlos Henrique de Cavalcante Carvalho',
    role: 'Sócio-Presidente | Especialista em Marketing e Negócios Internacionais',
    bio: 'Empresário, graduado em Marketing e especialista em Negócios Internacionais. Atua nacional e internacionalmente no desenvolvimento de estratégias que fortalecem marcas e ampliam presença institucional.',
    image: '/images/team/Carlos Henrique de Cavalcante Carvalho.png',
    email: 'contato@mako.ind.br',
    linkedin: 'https://www.linkedin.com/company/makosolucoesindustriais',
    order: 2,
  },
  {
    id: '3',
    name: 'Talles Eduardo Almeida de Assis',
    role: 'Sócio | Diretor',
    bio: 'Engenheiro Civil, Engenheiro de Segurança do Trabalho com MBA em Gerenciamento de Projetos. Ampla experiência em gestão, concepção e desenvolvimento de projetos industriais.',
    image: '/images/team/Talles Eduardo Almeida de Assis.png',
    email: 'contato@mako.ind.br',
    linkedin: 'https://www.linkedin.com/company/makosolucoesindustriais',
    order: 3,
  },
  {
    id: '4',
    name: 'Andreia Ribeiro Araújo',
    role: 'Gerente Financeira',
    bio: 'Administradora com MBA em Gestão de Empresas. Atuação estratégica nas áreas administrativa e financeira, com visão sistêmica e capacidade de integrar processos para maximizar desempenho organizacional.',
    image: '/images/team/Andreia Ribeiro Araújo.png',
    email: 'contato@mako.ind.br',
    linkedin: 'https://www.linkedin.com/company/makosolucoesindustriais',
    order: 4,
  },
]

export const mockClients: Client[] = [
  {
    id: '1',
    name: 'Indústria Alimentícia XYZ',
    logo: '/images/clients/client-1.png',
    website: 'https://client1.com',
    description: 'Soluções completas de automação para linha de produção',
    featured: true,
  },
  {
    id: '2',
    name: 'Metalúrgica ABC',
    logo: '/images/clients/client-2.png',
    website: 'https://client2.com',
    description: 'Automação de prensas e sistemas de controle',
    featured: true,
  },
  {
    id: '3',
    name: 'Química Brasil',
    logo: '/images/clients/client-3.png',
    description: 'Controle de processos químicos e segurança industrial',
    featured: false,
  },
  {
    id: '4',
    name: 'Têxtil Sul',
    logo: '/images/clients/client-4.png',
    description: 'Automação de tear e sistemas de qualidade',
    featured: false,
  },
  {
    id: '5',
    name: 'Logística Express',
    logo: '/images/clients/client-5.png',
    description: 'Sistemas de transporte e armazenagem automatizados',
    featured: false,
  },
  {
    id: '6',
    name: 'Energia Verde',
    logo: '/images/clients/client-6.png',
    description: 'Controle de sistemas de energia e monitoramento',
    featured: false,
  },
]

export const mockTestimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Roberto Mendes',
    role: 'Gerente de Manutenção',
    company: 'Indústria Alimentícia XYZ',
    image: '/images/testimonials/roberto.jpg',
    content: 'A Mako transformou completamente nosso processo produtivo. A automação instalada aumentou nossa produtividade em 40% e reduziu os índices de defeito. Equipe extremamente competente e dedicada.',
    rating: 5,
    featured: true,
  },
  {
    id: '2',
    name: 'Luciana Ferreira',
    role: 'Diretora Industrial',
    company: 'Metalúrgica ABC',
    image: '/images/testimonials/luciana.jpg',
    content: 'Contratamos a Mako para modernizar nossas prensas e o resultado superou todas as expectativas. O atendimento técnico foi excepcional e o projeto foi entregue no prazo.',
    rating: 5,
    featured: true,
  },
  {
    id: '3',
    name: 'Pedro Costa',
    role: 'Engenheiro Chefe',
    company: 'Química Brasil',
    image: '/images/testimonials/pedro.jpg',
    content: 'Os serviços de manutenção preventiva da Mako garantiram a estabilidade de nossas operações. Excelente suporte técnico e rápida resposta quando necessário.',
    rating: 4,
    featured: false,
  },
]

export const mockCompanyHistory: CompanyHistory[] = [
  {
    year: '2001',
    title: 'Fundação',
    description: 'Fundação da Mako Soluções Industriais em Fortaleza, Ceará. Atuação focada em parcerias estratégicas no setor industrial local.',
    image: '/images/history/2001.jpg',
  },
  {
    year: '2012',
    title: 'Consolidação e Credibilidade',
    description: 'Mais de 200 projetos industriais executados, com valores somados superiores a R$ 1,5 bilhão de reais.',
    image: '/images/history/2012.jpg',
  },
  {
    year: '2016',
    title: 'Premiações e Destaques',
    description: 'Reconhecimentos concedidos por líder do setor energético industrial, como Melhor Fornecedor de Serviços.',
    image: '/images/history/2016.jpg',
  },
  {
    year: '2022',
    title: 'Certificação ISO 9001',
    description: 'Conquista da certificação ISO 9001 para Elaboração de Projetos Industriais. Marco técnico crucial.',
    image: '/images/history/2022.jpg',
  },
  {
    year: '2023',
    title: 'Consultoria de Engenharia Integrada — Soluções em BIM',
    description: 'Integração de BIM para garantir projetos mais eficientes, sustentáveis e alinhados às melhores práticas de gestão.',
    image: '/images/history/2023.jpg',
  },
]

export const mockCertifications: Certification[] = [
  {
    id: '1',
    name: 'ISO 9001:2015',
    description: 'Sistema de Gestão da Qualidade para Elaboração de Projetos Industriais. Obtida em 2022.',
    image: '/images/certifications/iso-9001.jpg',
    validUntil: '2026-12-31',
    issuer: 'SGS Brasil',
  },
  {
    id: '2',
    name: 'NR-10',
    description: 'Segurança em Instalações e Serviços em Eletricidade.',
    image: '/images/certifications/nr-10.jpg',
    issuer: 'Ministério do Trabalho',
  },
  {
    id: '3',
    name: 'NR-12',
    description: 'Segurança no Trabalho em Máquinas e Equipamentos.',
    image: '/images/certifications/nr-12.jpg',
    issuer: 'Ministério do Trabalho',
  },
  {
    id: '4',
    name: 'NR-13',
    description: 'Segurança na operação de caldeiras e vasos de pressão.',
    image: '/images/certifications/nr-13.jpg',
    issuer: 'Ministério do Trabalho',
  },
  {
    id: '5',
    name: 'NR-18',
    description: 'Segurança e Saúde na Indústria da Construção.',
    image: '/images/certifications/nr-18.jpg',
    issuer: 'Ministério do Trabalho',
  },
]