import { Service, TeamMember, Client, Testimonial, CompanyHistory, Certification } from '@/types'
export const mockServices: Service[] = [
  {
    id: '1',
    slug: 'projetos-de-automacao',
    name: 'Projetos de Automação',
    description: 'Desenvolvimento completo de projetos de automação industrial sob medida.',
    fullDescription: 'Oferecemos desenvolvimento completo de projetos de automação industrial, desde o concepção inicial até a implementação final. Nossa equipe técnica qualificada projeta sistemas eficientes que otimizam processos e aumentam a produtividade.',
    icon: 'settings',
    image: '/images/services/automacao.jpg',
    benefits: [
      'Aumento da produtividade',
      'Redução de custos operacionais',
      'Melhoria da qualidade do produto',
      'Segurança operacional',
      'Monitoramento em tempo real',
    ],
    process: [
      {
        id: '1',
        title: 'Análise e Diagnóstico',
        description: 'Estudo detalhado do processo atual e identificação de oportunidades de melhoria.',
        icon: 'search',
        duration: '5-7 dias',
      },
      {
        id: '2',
        title: 'Projeto Conceitual',
        description: 'Desenvolvimento da solução técnica e definição dos requisitos do sistema.',
        icon: 'drafting-compass',
        duration: '3-5 dias',
      },
      {
        id: '3',
        title: 'Implementação',
        description: 'Instalação e configuração dos equipamentos e sistemas de automação.',
        icon: 'wrench',
        duration: '10-20 dias',
      },
      {
        id: '4',
        title: 'Comissionamento',
        description: 'Testes, ajustes finos e treinamento da equipe operacional.',
        icon: 'play-circle',
        duration: '2-3 dias',
      },
    ],
    duration: '20-35 dias',
    featured: true,
    tags: ['automacao', 'projetos', 'consultoria'],
  },
  {
    id: '2',
    slug: 'manutencao-industrial',
    name: 'Manutenção Preventiva e Corretiva',
    description: 'Serviços completos de manutenção para garantir a disponibilidade de seus equipamentos.',
    fullDescription: 'Nossos serviços de manutenção industrial visam garantir a máxima disponibilidade e vida útil dos seus equipamentos. Atuamos tanto na manutenção preventiva quanto na corretiva, com equipes especializadas e rápida resposta.',
    icon: 'tool',
    image: '/images/services/manutencao.jpg',
    benefits: [
      'Redução de paradas não planejadas',
      'Aumento da vida útil dos equipamentos',
      'Economia a longo prazo',
      'Segurança operacional',
      'Disponibilidade 24/7',
    ],
    process: [
      {
        id: '1',
        title: 'Diagnóstico',
        description: 'Avaliação do estado atual dos equipamentos e identificação de necessidades.',
        icon: 'clipboard-list',
        duration: '1-2 dias',
      },
      {
        id: '2',
        title: 'Planejamento',
        description: 'Definição do cronograma e recursos necessários para a manutenção.',
        icon: 'calendar',
        duration: '1 dia',
      },
      {
        id: '3',
        title: 'Execução',
        description: 'Realização dos serviços de manutenção programada ou emergencial.',
        icon: 'wrench',
        duration: 'Variável',
      },
      {
        id: '4',
        title: 'Verificação',
        description: 'Testes de funcionamento e entrega do equipamento em perfeitas condições.',
        icon: 'check-circle',
        duration: '1 dia',
      },
    ],
    duration: 'Conforme necessidade',
    featured: true,
    tags: ['manutencao', 'suporte', 'corretiva', 'preventiva'],
  },
  {
    id: '3',
    slug: 'treinamento-tecnico',
    name: 'Treinamento Técnico',
    description: 'Capacitação prática para equipes operacionais e de manutenção.',
    fullDescription: 'Oferecemos programas de treinamento técnico desenvolvidos para capacitar equipes na operação e manutenção de sistemas de automação industrial. Cursos práticos com foco nas necessidades específicas de cada cliente.',
    icon: 'graduation-cap',
    image: '/images/services/treinamento.jpg',
    benefits: [
      'Equipes capacitadas e autônomas',
      'Redução de chamados de suporte',
      'Operação mais eficiente',
      'Segurança no trabalho',
      'Atualização tecnológica',
    ],
    process: [
      {
        id: '1',
        title: 'Levantamento de Necessidades',
        description: 'Identificação das competências e conhecimentos necessários.',
        icon: 'users',
        duration: '1 dia',
      },
      {
        id: '2',
        title: 'Programação',
        description: 'Desenvolvimento do conteúdo e definição do cronograma do treinamento.',
        icon: 'calendar-alt',
        duration: '2-3 dias',
      },
      {
        id: '3',
        title: 'Execução do Treinamento',
        description: 'Aulas teóricas e práticas com equipamentos reais.',
        icon: 'chalkboard-teacher',
        duration: '2-5 dias',
      },
      {
        id: '4',
        title: 'Avaliação',
        description: 'Testes práticos e certificação dos participantes.',
        icon: 'award',
        duration: '1 dia',
      },
    ],
    duration: '8-15 horas',
    featured: false,
    tags: ['treinamento', 'capacitacao', 'curso'],
  },
]

export const mockTeamMembers: TeamMember[] = [
  {
    id: '1',
    name: 'Henrique Daniel de Cavalcante Carvalho',
    role: 'Sócio-Presidente | Fundador',
    bio: 'Engenheiro Civil, empresário e escritor, é fundador e Sócio-Presidente da empresa. Possui sólida atuação nas áreas de gerenciamento, qualidade total e projetos industriais, acumulando mais de 30 anos de experiência.',
    image: '/images/team/Henrique Daniel de Cavalcante Carvalho.png',
    email: 'contato@mako.ind.br',
    linkedin: 'https://www.linkedin.com/company/makosolucoesindustriais',
    order: 1,
  },
  {
    id: '2',
    name: 'Carlos Henrique de Cavalcante Carvalho',
    role: 'Sócio-Presidente | Especialista em Marketing e Negócios Internacionais',
    bio: 'Empresário, graduado em Marketing e especialista em Negócios Internacionais. Atua nacional e internacionalmente no desenvolvimento de estratégias que fortalecem marcas e ampliam presença institucional.',
    image: '/images/team/Carlos Henrique de Cavalcante Carvalho.png',
    email: 'contato@mako.ind.br',
    linkedin: 'https://www.linkedin.com/company/makosolucoesindustriais',
    order: 2,
  },
  {
    id: '3',
    name: 'Talles Eduardo Almeida de Assis',
    role: 'Sócio | Diretor',
    bio: 'Engenheiro Civil, Engenheiro de Segurança do Trabalho com MBA em Gerenciamento de Projetos. Ampla experiência em gestão, concepção e desenvolvimento de projetos industriais.',
    image: '/images/team/Talles Eduardo Almeida de Assis.png',
    email: 'contato@mako.ind.br',
    linkedin: 'https://www.linkedin.com/company/makosolucoesindustriais',
    order: 3,
  },
  {
    id: '4',
    name: 'Andreia Ribeiro Araújo',
    role: 'Gerente Financeira',
    bio: 'Administradora com MBA em Gestão de Empresas. Atuação estratégica nas áreas administrativa e financeira, com visão sistêmica e capacidade de integrar processos para maximizar desempenho organizacional.',
    image: '/images/team/Andreia Ribeiro Araújo.png',
    email: 'contato@mako.ind.br',
    linkedin: 'https://www.linkedin.com/company/makosolucoesindustriais',
    order: 4,
  },
]

export const mockClients: Client[] = [
  {
    id: '1',
    name: 'Indústria Alimentícia XYZ',
    logo: '/images/clients/client-1.png',
    website: 'https://client1.com',
    description: 'Soluções completas de automação para linha de produção',
    featured: true,
  },
  {
    id: '2',
    name: 'Metalúrgica ABC',
    logo: '/images/clients/client-2.png',
    website: 'https://client2.com',
    description: 'Automação de prensas e sistemas de controle',
    featured: true,
  },
  {
    id: '3',
    name: 'Química Brasil',
    logo: '/images/clients/client-3.png',
    description: 'Controle de processos químicos e segurança industrial',
    featured: false,
  },
  {
    id: '4',
    name: 'Têxtil Sul',
    logo: '/images/clients/client-4.png',
    description: 'Automação de tear e sistemas de qualidade',
    featured: false,
  },
  {
    id: '5',
    name: 'Logística Express',
    logo: '/images/clients/client-5.png',
    description: 'Sistemas de transporte e armazenagem automatizados',
    featured: false,
  },
  {
    id: '6',
    name: 'Energia Verde',
    logo: '/images/clients/client-6.png',
    description: 'Controle de sistemas de energia e monitoramento',
    featured: false,
  },
]

export const mockTestimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Roberto Mendes',
    role: 'Gerente de Manutenção',
    company: 'Indústria Alimentícia XYZ',
    image: '/images/testimonials/roberto.jpg',
    content: 'A Mako transformou completamente nosso processo produtivo. A automação instalada aumentou nossa produtividade em 40% e reduziu os índices de defeito. Equipe extremamente competente e dedicada.',
    rating: 5,
    featured: true,
  },
  {
    id: '2',
    name: 'Luciana Ferreira',
    role: 'Diretora Industrial',
    company: 'Metalúrgica ABC',
    image: '/images/testimonials/luciana.jpg',
    content: 'Contratamos a Mako para modernizar nossas prensas e o resultado superou todas as expectativas. O atendimento técnico foi excepcional e o projeto foi entregue no prazo.',
    rating: 5,
    featured: true,
  },
  {
    id: '3',
    name: 'Pedro Costa',
    role: 'Engenheiro Chefe',
    company: 'Química Brasil',
    image: '/images/testimonials/pedro.jpg',
    content: 'Os serviços de manutenção preventiva da Mako garantiram a estabilidade de nossas operações. Excelente suporte técnico e rápida resposta quando necessário.',
    rating: 4,
    featured: false,
  },
]

export const mockCompanyHistory: CompanyHistory[] = [
  {
    year: '2015',
    title: 'Fundação da Mako',
    description: 'Início das atividades com foco em soluções de automção para pequenas e médias indústrias.',
    image: '/images/history/2015.jpg',
  },
  {
    year: '2017',
    title: 'Expansão do Portfólio',
    description: 'Ampliação da linha de produtos e serviços, incluindo manutenção industrial completa.',
    image: '/images/history/2017.jpg',
  },
  {
    year: '2019',
    title: 'Certificação ISO 9001',
    description: 'Conquista da certificação ISO 9001, reconhecendo a qualidade de nossos processos.',
    image: '/images/history/2019.jpg',
  },
  {
    year: '2021',
    title: 'Digitalização de Serviços',
    description: 'Implementação de sistemas de monitoramento remoto e suporte técnico 24/7.',
    image: '/images/history/2021.jpg',
  },
  {
    year: '2023',
    title: 'Expansão Nacional',
    description: 'Abertura de filiais em outros estados e consolidação como referência nacional.',
    image: '/images/history/2023.jpg',
  },
]

export const mockCertifications: Certification[] = [
  {
    id: '1',
    name: 'ISO 9001:2015',
    description: 'Sistema de Gestão da Qualidade para projeto e implementação de soluções de automação industrial.',
    image: '/images/certifications/iso-9001.jpg',
    validUntil: '2026-12-31',
    issuer: 'SGS Brasil',
  },
  {
    id: '2',
    name: 'ABNT NBR 5410',
    description: 'Certificação em instalações elétricas de baixa tensão conforme normas brasileiras.',
    image: '/images/certifications/nbr-5410.jpg',
    validUntil: '2025-12-31',
    issuer: 'ABNT',
  },
  {
    id: '3',
    name: 'NR-12',
    description: 'Segurança no Trabalho em Máquinas e Equipamentos.',
    image: '/images/certifications/nr-12.jpg',
    issuer: 'Ministério do Trabalho',
  },
  {
    id: '4',
    name: 'Certificação de Competência Técnica',
    description: 'Reconhecimento da competência técnica em automção industrial.',
    image: '/images/certifications/competencia-tecnica.jpg',
    validUntil: '2026-06-30',
    issuer: 'CREA-CE',
  },
]